esp32:
  board: lolin_s2_mini
  variant: ESP32S2
  cpu_frequency: 240MHZ
  framework:
    type: arduino

packages:
  diagnostics: !include 
    file: ../include/diagnostics.yaml
  blinky: !include
    file: ../include/interval-blinky.yaml
    vars:
      builtin_led_pin: "GPIO15"
  wifi: !include  
    file: ../include/wifi.yaml
  i2c: !include
    file: ../include/i2c.yaml
    vars:
      i2c_sda_pin: "GPIO21"
      i2c_scl_pin: "GPIO18"
      i2c_freq: "256kHz"  # on this board, >= 258kHz will not work with the BMP280 module
  temp_humidity: !include
    file: ../include/BMP280-AHT20-temp-humidity.yaml
    vars: 
      temperature_offset: "0"      
  illuminance: !include
    file: ../include/photoresistor-illuminance.yaml
    vars:
      illuminance_pin: "GPIO2"





# "All Device" baseline stuff here

<<: !include 
  file: ../include/esp32-device-baseline.yaml
  vars:
    device_hostname: "910-esphome"
    device_friendly_name: "910-esphome"
    device_comment: "Board 910 configured as Environmental Sensor."

